
export const REQUEST_REPORTS = 'REQUEST_REPORTS';
export const RECEIVE_REPORTS = 'RECEIVE_REPORTS';

export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const REQUEST_LOCK_USER = 'REQUEST_LOCK_USER';
export const RECEIVE_LOCK_USER = 'RECEIVE_LOCK_USER';

export const REQUEST_WARN_USER = 'REQUEST_WARN_USER';
export const RECEIVE_WARN_USER = 'RECEIVE_WARN_USER';

export const REQUEST_UNLOCK_USER = 'REQUEST_UNLOCK_USER';
export const RECEIVE_UNLOCK_USER = 'RECEIVE_UNLOCK_USER';